"""initial_schema

Revision ID: 071cabf1b683
Revises: 
Create Date: 2026-06-18 02:58:38.394261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '071cabf1b683'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('rubric_id', sa.String(length=36), nullable=True),
    sa.Column('debrief_count', sa.Integer(), nullable=True),
    sa.Column('has_synthesis', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('reports',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('reviewer_name', sa.String(length=255), nullable=True),
    sa.Column('reviewer_approved', sa.Boolean(), nullable=True),
    sa.Column('final_reviewer_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('debriefs',
    sa.Column('debrief_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('interviewer_name', sa.String(length=255), nullable=False),
    sa.Column('round_name', sa.String(length=255), nullable=True),
    sa.Column('interview_date', sa.String(length=50), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('score_raw', sa.String(length=50), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('debrief_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('debriefs')
    op.drop_table('reports')
    op.drop_table('projects')
    # ### end Alembic commands ###
